-- Additive migration: the legacy uptimeflare/state row is deliberately preserved.
CREATE TABLE IF NOT EXISTS uptimeflare (key TEXT PRIMARY KEY, value BLOB NOT NULL);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
INSERT OR IGNORE INTO settings VALUES ('page', '{"title":"服务状态","description":"服务运行情况与维护进展"}');
CREATE TABLE groups (id TEXT PRIMARY KEY, name TEXT NOT NULL, position INTEGER NOT NULL DEFAULT 0, version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE components (id TEXT PRIMARY KEY, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', group_id TEXT REFERENCES groups(id) ON DELETE SET NULL, public INTEGER NOT NULL DEFAULT 1, position INTEGER NOT NULL DEFAULT 0, link TEXT NOT NULL DEFAULT '', version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE monitors (id TEXT PRIMARY KEY, name TEXT NOT NULL, component_id TEXT NOT NULL REFERENCES components(id), config TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, interval INTEGER NOT NULL DEFAULT 60, grace INTEGER NOT NULL DEFAULT 180, notify INTEGER NOT NULL DEFAULT 1, version INTEGER NOT NULL DEFAULT 1, next_check_at INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL);
CREATE INDEX monitors_due ON monitors(enabled, next_check_at);
CREATE TABLE monitor_state (monitor_id TEXT PRIMARY KEY REFERENCES monitors(id) ON DELETE CASCADE, status TEXT NOT NULL, checked_at INTEGER NOT NULL, latency INTEGER NOT NULL, version INTEGER NOT NULL, failure_since INTEGER, alerted INTEGER NOT NULL DEFAULT 0, result_id TEXT NOT NULL);
CREATE TABLE check_jobs (id TEXT PRIMARY KEY, monitor_id TEXT NOT NULL REFERENCES monitors(id) ON DELETE CASCADE, version INTEGER NOT NULL, scheduled_at INTEGER NOT NULL, state TEXT NOT NULL DEFAULT 'pending', lease_until INTEGER NOT NULL DEFAULT 0, token TEXT, attempts INTEGER NOT NULL DEFAULT 0);
CREATE INDEX jobs_dispatch ON check_jobs(state, lease_until);
CREATE TABLE check_results (id TEXT PRIMARY KEY, monitor_id TEXT NOT NULL REFERENCES monitors(id) ON DELETE CASCADE, checked_at INTEGER NOT NULL, up INTEGER NOT NULL, latency INTEGER NOT NULL, reason TEXT NOT NULL, location TEXT NOT NULL);
CREATE INDEX results_monitor_time ON check_results(monitor_id, checked_at);
CREATE TABLE monitor_outages (id TEXT PRIMARY KEY, monitor_id TEXT NOT NULL REFERENCES monitors(id) ON DELETE CASCADE, start_at INTEGER NOT NULL, end_at INTEGER, reason TEXT NOT NULL);
CREATE INDEX outages_monitor_time ON monitor_outages(monitor_id, start_at);
CREATE UNIQUE INDEX outages_open ON monitor_outages(monitor_id) WHERE end_at IS NULL;
CREATE TABLE daily_stats (monitor_id TEXT NOT NULL REFERENCES monitors(id) ON DELETE CASCADE, day INTEGER NOT NULL, up_seconds INTEGER NOT NULL DEFAULT 0, down_seconds INTEGER NOT NULL DEFAULT 0, latency_sum INTEGER NOT NULL DEFAULT 0, samples INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(monitor_id, day));
CREATE TABLE events (id TEXT PRIMARY KEY, kind TEXT NOT NULL, title TEXT NOT NULL, status TEXT NOT NULL, severity TEXT NOT NULL, start_at INTEGER NOT NULL, end_at INTEGER, published INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, version INTEGER NOT NULL DEFAULT 1);
CREATE INDEX events_history ON events(published, start_at);
CREATE TABLE event_components (event_id TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE, component_id TEXT NOT NULL REFERENCES components(id), PRIMARY KEY(event_id, component_id));
CREATE TABLE event_updates (id TEXT PRIMARY KEY, event_id TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE, status TEXT NOT NULL, body TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE INDEX updates_event_time ON event_updates(event_id, created_at);
CREATE TABLE notification_channels (id TEXT PRIMARY KEY, name TEXT NOT NULL, config TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE notification_outbox (id TEXT PRIMARY KEY, channel_id TEXT NOT NULL REFERENCES notification_channels(id) ON DELETE CASCADE, message TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'pending', attempts INTEGER NOT NULL DEFAULT 0, available_at INTEGER NOT NULL, lease_until INTEGER NOT NULL DEFAULT 0, token TEXT, error TEXT, created_at INTEGER NOT NULL);
CREATE INDEX outbox_pending ON notification_outbox(state, available_at, lease_until);
CREATE TABLE attachments (id TEXT PRIMARY KEY, object_key TEXT UNIQUE NOT NULL, name TEXT NOT NULL, content_type TEXT NOT NULL, size INTEGER NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE event_attachments (event_id TEXT NOT NULL REFERENCES events(id) ON DELETE CASCADE, attachment_id TEXT NOT NULL REFERENCES attachments(id), PRIMARY KEY(event_id, attachment_id));
CREATE TABLE audit_logs (id TEXT PRIMARY KEY, actor TEXT NOT NULL, action TEXT NOT NULL, resource TEXT NOT NULL, created_at INTEGER NOT NULL);
CREATE TABLE import_runs (id TEXT PRIMARY KEY, created_at INTEGER NOT NULL);
CREATE TABLE result_guard (id TEXT PRIMARY KEY, ok INTEGER NOT NULL CHECK(ok=1));
